[package]
name = "ds4l"
version = "0.1.0"
edition = "2021"

[dependencies]
hidapi = "2.6"
libc = "0.2"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
dirs = "6"
crc32fast = "1.5"

[lib]
name = "ds4l"
path = "src/lib.rs"

[[bin]]
name = "ds4l"
path = "src/main.rs"

[[bin]]
name = "virtual_ds4_test"
path = "src/bin/virtual_ds4_test.rs"

[[bin]]
name = "passthrough_test"
path = "src/bin/passthrough_test.rs"

[[bin]]
name = "gyro_stick_test"
path = "src/bin/gyro_stick_test.rs"

[[bin]]
name = "touchpad_test"
path = "src/bin/touchpad_test.rs"

[[bin]]
name = "ds4l_daemon"
path = "src/bin/ds4l_daemon.rs"

[[bin]]
name = "bluetooth_test"
path = "src/bin/bluetooth_test.rs"
